name: Ruby CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Install dependencies
      run: gem install rspec
      working-directory: Ruby
    - name: Run tests
      run: rspec
      working-directory: Ruby